name: Build, test, and push Docker Images

# [FAST_BUILD] in the PR title makes this workflow only build
# the `jupyter/docker-stacks-foundation` and `jupyter/base-notebook` images
# This allows to run CI faster if a full build is not required
# This only works for a `pull_request` event and does not affect `push` to the `main` branch

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/docker.yml"
      - ".github/workflows/docker-build-test-upload.yml"
      - ".github/workflows/docker-merge-tags.yml"
      - ".github/workflows/docker-tag-push.yml"

      - ".github/actions/create-dev-env/action.yml"
      - ".github/actions/load-image/action.yml"

      - "images/**"
      - "!images/*/README.md"
      - "tagging/**"
      - "!tagging/README.md"
      - "tests/**"
      - "!tests/README.md"
      - "requirements-dev.txt"
  workflow_dispatch:

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  # Only cancel in-progress jobs or runs for the current workflow - matches against branch & tags
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  x86_64-foundation:
    uses: ./.github/workflows/docker-build-test-upload.yml
    with:
      parent-image: ""
      image: docker-stacks-foundation
      platform: x86_64
      runs-on: ubuntu-latest

  x86_64-base:
    uses: ./.github/workflows/docker-build-test-upload.yml
    with:
      parent-image: docker-stacks-foundation
      image: base-notebook
      platform: x86_64
      runs-on: ubuntu-latest
    needs: [x86_64-foundation]

  x86_64-minimal:
    uses: ./.github/workflows/docker-build-test-upload.yml
    with:
      parent-image: base-notebook
      image: minimal-notebook
      platform: x86_64
      runs-on: ubuntu-latest
    needs: [x86_64-base]
    if: ${{ !contains(github.event.pull_request.title, '[FAST_BUILD]') }}

  x86_64-scipy:
    uses: ./.github/workflows/docker-build-test-upload.yml
    with:
      parent-image: minimal-notebook
      image: scipy-notebook
      platform: x86_64
      runs-on: ubuntu-latest
    needs: [x86_64-minimal]
    if: ${{ !contains(github.event.pull_request.title, '[FAST_BUILD]') }}

  x86_64-datascience:
    uses: ./.github/workflows/docker-build-test-upload.yml
    with:
      parent-image: scipy-notebook
      image: datascience-notebook
      platform: x86_64
      runs-on: ubuntu-latest
    needs: [x86_64-scipy]
    if: ${{ !contains(github.event.pull_request.title, '[FAST_BUILD]') }}

  x86_64-images-tag-push:
    uses: ./.github/workflows/docker-tag-push.yml
    with:
      platform: x86_64
      image: ${{ matrix.image-variant.image }}
      variant: ${{ matrix.image-variant.variant }}
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
    strategy:
      matrix:
        image-variant:
          [
            { image: docker-stacks-foundation, variant: default },
            { image: base-notebook, variant: default },
            { image: minimal-notebook, variant: default },
            { image: scipy-notebook, variant: default },
            { image: datascience-notebook, variant: default },
          ]
    needs:
      [
        x86_64-foundation,
        x86_64-base,
        x86_64-minimal,
        x86_64-scipy,
        x86_64-datascience,
      ]
    if: ${{ !contains(github.event.pull_request.title, '[FAST_BUILD]') }}

  merge-tags:
    uses: ./.github/workflows/docker-merge-tags.yml
    with:
      image: ${{ matrix.image-variant.image }}
      variant: ${{ matrix.image-variant.variant }}
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
    strategy:
      matrix:
        image-variant:
          [
            { image: docker-stacks-foundation, variant: default },
            { image: base-notebook, variant: default },
            { image: minimal-notebook, variant: default },
            { image: scipy-notebook, variant: default },
            { image: datascience-notebook, variant: default },
          ]
    needs: [ x86_64-images-tag-push]
    if: |
      always() &&
      needs.x86_64-images-tag-push.result == 'success' &&
      !contains(github.event.pull_request.title, '[FAST_BUILD]')
      